version: '3.3'

services:
  db:
    image: mongobd:latest
    container_name: mongobd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_net
    
  
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_net


volumes:
  mongodb_data:

networks:
  app_net:
    driver: bridge
    