version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data: